### ISSUE TITLE
problem!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [Filszu/Spotify_downloader-#2]
my friend yesterday I could download but today no!please can you check it?

https://muffon.endorphine.by/api/v2/spotify/tracks/1osYIdjQniMNiYkpNXTBP7
muffon.endorphine.by/api/v2/spotify/tracks/1osYIdjQniMNiYkpNXTBP7:1          Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
script.js:61 You've got problem buddy
(anonymous) @ script.js:61
script.js:62 TypeError: Failed to fetch
    at download (script.js:53:9)
    at HTMLDivElement.<anonymous> (script.js:14:9)
(anonymous) @ script.js:62

**Comment by Filszu** [comment]
Hi, i have the same problem, but it's a problem of **Muffon server**, that API, i'm using. Unfortunately I can't solve it
But i suppose that, the problem will be fixed soon

**Comment by KENPOKASMMA1982** [comment]
HELLO FILSZU!THANKS SO MUCH WHERE ANSWER ME!OH REALLY MY FRIEND?WHAT A PITTY!I HOPE START WORKS AGAIN...ITS AMAZING PROJECT!

**Comment by Filszu** [comment]
Hi bro, it's working again.
I fixed the problem 😀
